### PR TITLE
Milestone 1: Heatmap teardown of the Smashing Magazine Homepage

### PR DESCRIPTION
**Pull request by tiagoit**
# Smashing Magazine Teardown
Heatmap teardown of the Smashing Magazine Homepage

### Technology

HTML, CSS3

### Authors

- **Tiago Ferreira** - [@ferreirati](https://github.com/ferreirati)
- **Tiffany Arellano** - [@yirano](https://github.com/yirano)

### Links

- **Assignment page** - [The Odin Project](https://www.theodinproject.com/courses/html5-and-css3/lessons/design-teardown)

### CODE REVIEW

**Review by uche-inyama — COMMENTED** [review]
## Hi team, nice job :slightly_smiling_face: 

### Just few adjustments to make.

 - [ ] Each of the articles, should be wrapped with an ```<article>``` tag.

- [ ] Use of the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) to wrap the dominant content of the `<body>` in  your document

- [ ] Use ```div``` tag to position elements after the ```nav``` tag. You can inspect the source page for reference.

[**Note**] 
          -   In your subsequent projects, use a descriptive name for your pull request,
          -  Also, after implementing changes, requested from a TSE, make a comment, highlighting the 
             summary of the changes you have implemented, in the pull request. :slightly_smiling_face: 

### After implementing these changes submit another form for code review.

**Comment by yirano** [comment]
> ## Hi team, nice job 🙂
> ### Just few adjustments to make.
> * [ ]  Each of the articles, should be wrapped with an `<article>` tag.
> * [ ]  Use of the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) to wrap the dominant content of the `<body>` in  your document
> * [ ]  Use `div` tag to position elements after the `nav` tag. You can inspect the source page for reference.
> 
> [**Note**]
> - In your subsequent projects, use a descriptive name for your pull request,
> - Also, after implementing changes, requested from a TSE, make a comment, highlighting the
> summary of the changes you have implemented, in the pull request. 🙂
> 
> ### After implementing these changes submit another form for code review.

The reason why those weren't wrapped in an <article> tag was because those aren't technically articles, but rather an excerpt-link to the the actual article itself. I will come up with a better name to describe its class name, but I believe those changes aren't necessary.

**Comment by ebukaume** [comment]
Hi @ferreirati and @yirano 

Nice work :smiley: so far. Just one time left.

## [REQUIRED]
**Footer**
 - [ ] It contains centered links.

It seems you guys forgot to make them links. The affected region can be referenced [Here](https://github.com/yirano/mv-05-htmlcss-smashingmag/blob/a5a1249d831a08097dbb412d1dcf09022b494378/src/index.html#L449).

**Please kindly submit another code review request after effecting the requested changes.** :v:

**Comment by ebukaume** [comment]
**Congratulations team!**

We are now green! You guys can go ahead and merge this PR.

Good luck with your next projects... :clap:

**Pull request merged**
